### ISSUE TITLE
Program doesn't block if email is not setup

### ISSUE THREAD

**Issue by maatimati** [claristorio/Gmail-IP-updater-DISCONTINUED#2]
error code:
Traceback (most recent call last):
  File "apscheduler\executors\base.py", line 125, in run_job
  File "ipUpdater.py", line 82, in check
  File "ipUpdater.py", line 70, in sendEmail
  File "smtplib.py", line 734, in login
  File "smtplib.py", line 637, in auth
  File "smtplib.py", line 427, in docmd
  File "smtplib.py", line 400, in getreply
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

should return custom error message

**Comment by Tittiere** [comment]
Solved, added "smtplib.SMTPServerDisconnected" as an error type
